name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '1 0 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install black flake8 isort
          python -m pip install hypothesis pytest pytest-cov
          python setup.py install
          python -m pip list
      - name: Lint with `black`
        if: matrix.python-version == 3.8 && matrix.os == 'ubuntu-latest'
        run: |
          python -m black --check --diff -l 80 .
      - name: Lint with `flake8`
        if: matrix.python-version == 3.8 && matrix.os == 'ubuntu-latest'
        run: |
          python -m flake8 --max-line-length=80 .
      - name: Lint with `isort`
        if: matrix.python-version == 3.8 && matrix.os == 'ubuntu-latest'
        run: |
          python -m isort -w 80 -m 3 --trailing-comma --check-only .
      - name: Run tests
        run: |
          python -m pytest --cov=dogma --cov-fail-under=100 tests
